### ISSUE TITLE
Issues with cloning repository

### ISSUE THREAD

**Issue by vydeng** [comp426-2023-spring/a00#4]
When I try to follow the directions to clone with the SSH key, I encounter the following:

git clone git@github.com:comp426-2023-spring/a00-onboarding-vydeng.git
Cloning into 'a00-onboarding-vydeng'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I'm not sure what's going wrong. I had to set up my new key in .ssh/new_id_rsa because id_rsa already existed, but other than that I think I followed the directions exactly.

**Comment by jdmar3** [comment]
First, you can use the contents of `.ssh/id_rsa.pub` as the content of the key in your GitHub settings. If you already have a key set up, then you don't need a new key. 

Second, you should be using the file with the `.pub` extension. You never want to put the contents of the other one anywhere other than on your local system.

My guess is that you copied the contents of a PRIVATE key rather than a PUBLIC key to GitHub and that means that your authentication is broken. Retrace your steps and make sure that you are using the PUBLIC key to import into your GitHub settings and that should sort you out, hopefully.

**Comment by daqichen** [comment]
From [Github help doc](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey):

You should verify your connection by typing:
```
$ ssh -T git@github.com
> Hi USERNAME! You've successfully authenticated...
```

If you do indeed need to delete one of the SSH keys, the end of the article also walks through that.

Hope this helps!

**Comment by daqichen** [comment]
@vydeng Just checking in to see if this issue has been resolved?

**Comment by vydeng** [comment]
Yes thank you!! I had to add the key again but it works now.
